remote_theme: abhinavs/moonwalk
title: Mira's writings
author: Mira Ojamo
description: >
  Mira's different writings: Blog, fanfiction, random memos - anything found between my two ears!
  The content is mixed between Finnish and English as I'm native finnish and fluent in English.

markdown: kramdown
url: writings.ojamo.fi
highlighter: rouge

exclude:
  - "cyberturku_fanfic/README.md"

theme_config:
  appearance: "dark"
  show_navbar: true
  show_footer: false
  show_description: true
  date_format: "%Y-%m-%d"
  back_home_text: "home.."
  show_copyright: true
  show_fanfics: true
  show_projects: false
  show_misc_list: false
  show_reading_time: true

  home:
    title_fanfic: Fanfiction
    title_projects: Projects
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Other things
    desc_fanfic: Smutty fanfiction about Cyberpunk 2020 TTRPG campaing I'm playing in. Main ship is my character and her deceased wife. Mostly in Finnish