remote_theme: abhinavs/moonwalk
title: Ojamo.fi
description: "Mira's writings: Blog, fanfiction, random memos - anything found between my two ears!"
markdown: kramdown
url: writings.ojamo.fi
theme_config:
  appearance: "dark"
  show_navbar: true
  show_footer: false
  show_description: true