remote_theme: abhinavs/moonwalk
title: Mira's writings
author: Mira Ojamo
tagline: Mira's writing corner
locale: en_US
description: >
  Mira's different writings: Blog, fanfiction, random memos - anything found between my two ears!
  The content is mixed between Finnish and English as I'm native finnish and fluent in English.

markdown: kramdown
url: writings.ojamo.fi
highlighter: rouge

social:
  name: Mira Ojamo / Siikakala
  links:
    - https://instagrom.com/siikakala
    - https://www.facebook.com/siikakala
    - https://twitter.com/siikakala
    - https://www.linkedin.com/in/siikakala
    - https://github.com/siikakala

permalink: /:categories/:slug

collections:
  - characters

defaults:
  - scope:
      path: "fanfics"
      type: "posts"
    values:
      layout: "fanfic_post"
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog_post"

theme_config:
  appearance: "dark"
  appearance_toggle: true
  show_navbar: true
  show_footer: true
  show_description: true
  show_tags: true
  date_format: "%Y-%m-%d"
  back_home_text: "home.."
  show_copyright: true
  show_fanfics: true
  show_blog: true
  show_projects: false
  show_misc_list: false
  show_reading_time: true

  home:
    title_fanfic: Fanfiction
    title_projects: Projects
    title_misc_list: Details
    title_blog: Personal Blog
    title_old_projects: Other things
    desc_fanfic: Smutty fanfiction about Cyberpunk 2020 TTRPG campaing I'm playing in. Main ship is my Australian character Elena and her now-deceased Finnish wife, Heidi. Mostly in Finnish
    desc_blog: Personal blog. Rambling about life, finnish conventions, work (generalized - NDA), D&D, DMing, LAN parties, and ..life. Mostly in English

plugins:
  - jemoji